### ISSUE TITLE
Can't reproduce the performance as listed in README.md

### ISSUE THREAD

**Issue by ciychen** [intelcaffe/caffe#1]
Hi experts,

I'm now looking for a good DL framework to run alexNet, and I found intelcaffe-master speedup x5.7 compared with bvlc-caffe-master. So I followed the instructions to setup my environment, and ran intelcaffe, but got 2615.5ms for alexnet which was x2 compared with the data listed in README.md (intelcaffe-master 1297ms for alexnet). 
Not sure is there any mistakes in my setups. Can you help to look into my configs and provide me the correction direction? Thanks in advance!

Here's my test result:
-------------------------
I0315 10:14:47.221025 73417 caffe.cpp:463] Average Forward pass: 1097.3 ms.
I0315 10:14:47.221030 73417 caffe.cpp:465] Average Backward pass: 1518.19 ms.
I0315 10:14:47.221035 73417 caffe.cpp:467] Average Forward-Backward: 2615.5 ms.

Here's my configs
---------------------------
Caffe	        https://github.com/intelcaffe/caffe
CPU  	        Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
OS	                CentOS 6.6
Linux Kernel	3.10.99-1.el6.elrepo.x86_64
MKL	                11.3
GCC	                4.8.4
Packages:
	boost_1_53_0
        opencv-2.4.9
        protobuf-python-3.0.0-alpha-4
        glog-0.3.4
        gflags-2.1.2
        lmdb-LMDB_0.9.16
        leveldb-1.18
        hdf5-1.8.15

I used the fake alexnet benchmark from below link:
        https://github.com/soumith/convnet-benchmarks/tree/master/caffe/ 

run the following commands to get performance:
        export OMP_NUM_THREADS=36
        export KMP_AFFINITY=compact,granularity=fine
        cd intelcaffe
        ./build/tools/caffe time --model=./imagenet_winners/alexnet.prototxt --iterations=10  --logtostderr=1 >>output_alexnet.log 2>&1

Best Regards,
chency

**Comment by jczaja** [comment]
Thanks for giving a go to intelcaffe.

- Could you please rerun the test but NOT setting any exports? intelcaffe tries to determine on its own number of OpenMP threads to be used, and set threads affinity accordingly.
- Is your platform heaving disabled Hyperthreading (in BIOS). eg. please attach output of lscpu.
- when rerunning the test please use more iterations eg. 50

**Comment by ciychen** [comment]
Hi jczaja,

Thanks for your fast feedback!
After tried the your suggestions, without setting any exports and ran 50 iterations by below commands:
./build/tools/caffe time --model=./imagenet_winners/alexnet.prototxt --iterations=50  --logtostderr=1 >>output_alexnet.log 2>&1

I got the test result as below, which was still x2 compared with your test result.
------------------
I0316 09:23:24.211120 90909 caffe.cpp:463] Average Forward pass: 1089.39 ms.
I0316 09:23:24.211125 90909 caffe.cpp:465] Average Backward pass: 1508.32 ms.
I0316 09:23:24.211138 90909 caffe.cpp:467] Average Forward-Backward: 2597.76 ms.
I0316 09:23:24.211143 90909 caffe.cpp:469] Total Time: 129888 ms.


Here's the output from lscpu:
------------
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                36
On-line CPU(s) list:   0-35
Thread(s) per core:    1
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               1274.164
BogoMIPS:              4594.76
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-35


Any other suggestions on this? Thanks!

Best Regards,
chency

**Comment by intelmm** [comment]
Hi Chency,

Thank you for lscpu print. I can see one difference in comparison to our setup.
```
NUMA node(s): 2
NUMA node0 CPU(s): 0-17
NUMA node1 CPU(s): 18-35
```
The NUMA (Non-Uniform Memory Access) defines how CPU access memory. In your case all CPUs use single node. **Make sure, you have all RAM equally distributed between both banks and working @ 2133 MHz**. To print detailed information on RAM installed in your setup, type:
```
dmidecode --type memory
```
The indicator `Bank Locator: NODE #` tells to which node each memory device is physically connected. In your case all memories are connected to node 1 but should be connected to both node 1 and 2. Please tell us if this helped you or not.

Best Regards,
Mariusz Moczala

**Comment by ciychen** [comment]
Hi Mariusz Moczala,

Thanks for your information.
Actually, I have 8 DIMMs (each one is 16GB) on my board, each node has 4 DIMMs, and they're woking @2133MHz.
In my previous test result, I disabled "NUMA Optimization" in BIOS, so that's why "lscpu" only showed 1 NUMA node(s).
Then I enabled "NUMA Optimization" in BIOS, and got 2 NUMA node(s) same as your setup. 
But the performance was still not good as yours, what I got was: Average Forward-Backward: 2552.88 ms.

> root@hsw1:~# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                36
On-line CPU(s) list:   0-35
Thread(s) per core:    1
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               3567.425
BogoMIPS:              4595.46
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-17
NUMA node1 CPU(s):     18-35

I attached the test result of Alexnet ([output_alexnet.txt](https://github.com/intelcaffe/caffe/files/177189/output_alexnet.txt)) and dmidecode content ([dmidecode_content.txt](https://github.com/intelcaffe/caffe/files/177186/dmidecode_content.txt)), appreciate you can take a look and solve my problems.


Best Regards,
Chency

**Comment by intelmm** [comment]
Hi Chency,

Your setup now looks correct. However I have observed another differences. Beginning of your caffe output for Alexnet should looks like:

```
I0317 08:20:56.132442 129343 caffe.cpp:414] Use CPU.
I0317 08:20:56.137950 129343 cpu_info.cpp:340] Total number of sockets: 2
I0317 08:20:56.137991 129343 cpu_info.cpp:343] Total number of CPU cores: 36
I0317 08:20:56.138005 129343 cpu_info.cpp:346] Total number of processors: 36
I0317 08:20:56.138017 129343 cpu_info.cpp:349] GPU is used: no
I0317 08:20:56.138036 129343 cpu_info.cpp:352] OpenMP environmental variables are specified: yes
I0317 08:20:56.138052 129343 cpu_info.cpp:355] OpenMP thread bind allowed: no
I0317 08:20:56.141192 129343 cpu_info.cpp:358] Number of OpenMP threads: 36
I0317 08:20:56.141361 129343 net.cpp:327] The NetState phase (0) differed from the phase (1) specified by a rule in layer data
I0317 08:20:56.141403 129343 net.cpp:327] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I0317 08:20:56.141824 129343 net.cpp:62] Initializing net from parameters:
name: "AlexNet"
state {
```

Yours output does not tell anything about CPU/OpenMP configuration. Could you confirm please you have the newest version of intelcaffe master branch?

If so, do not use any of OpenMP environmental flags. Those flags are now recommended for debug purposes only. If you specify any (like `OMP_NUM_THREADS` or `KMP_AFFINITY`) it will disable part of internal intelcaffe optimizations.

One more thing. Please try to run alexnet with the following prototxt:
```
./build/tools/caffe time --model=models/bvlc_alexnet/train_val.prototxt
```

Best Regrads,
Mariusz

**Comment by ciychen** [comment]
Hi Mariusz Moczala,

One more info from my side, currently the benchmark I used was from [convnet-benchmarks](https://github.com/soumith/convnet-benchmarks/blob/master/caffe/imagenet_winners/alexnet.prototxt)
its batch size was 128.

Today, I change this prototype file to use input batch size 256  and some other parameters, please refer to 
[alexnet_256bsize.prototxt.txt](https://github.com/intelcaffe/caffe/files/177412/alexnet_256bsize.prototxt.txt), and I got the performance result even worse than the original one.

I0317 14:40:54.036620 34790 caffe.cpp:479] Average Forward pass: 2706.32 ms.
I0317 14:40:54.036626 34790 caffe.cpp:481] Average Backward pass: 3683.81 ms.
I0317 14:40:54.036631 34790 caffe.cpp:483] Average Forward-Backward: 6390.2 ms.
I0317 14:40:54.036636 34790 caffe.cpp:485] Total Time: 63902 ms.

Anything wrong with such topology file? Thanks in advance!


Best Regards,
Chency

**Comment by jczaja** [comment]
Hi,
Based on your description it seems that you are running single-threaded build of intelcaffe rather than multithreaded (OpenMP based) one. OpenMP build is default one and is to be disabled (eg. switching to non-OpenMP version) when Makefile / CMake file won't detect OpenMP capability within compiler or when user is explicitly asking for having non-OpenMP intelcaffe. 

Ok, so it seems there is a building issue. My first guess is that when building intelcaffe against MKL you are not setting MKL enviroment eg.
_source /opt/intel/mkl/bin/mklvars.sh intel64_
(There is an entry about that in BVLC/caffe/doc/installation.md , but it is missing in intelcaffe. We will fill that gap soon)

So, for example your building procedure should look like this:
* _source /opt/intel/mkl/bin/mklvars.sh intel64_
* Edit Makefile.config to set mkl as BLAS
* _make all test -j36_
* run your tests

Please write if you are setting MKL env vars, if not then please rebuild intelcaffe that way.
Also to make sure  if compilation options are all fine, you can attach compilation log from make dry run eg.
* _source /opt/intel/mkl/bin/mklvars.sh intel64_
* _make clean_
* Edit Makefile.config to set mkl as BLAS
*_make all test -n  # dry run, output full building compilation procedure log, but not actual building

Hope this will help,
Jacek

**Comment by ciychen** [comment]
Hi Mariusz Moczala and Jacek,

Thank you guys for your fast feedback and helpful information.
It seems that the OpenMP feature is not enabled on my platform.

The build step of using Makefile.config as below:

- source /opt/intel/mkl/bin/mklvars.sh intel64

- cp Makefile.config.example Makefile.config

- uncomment CPU_ONLY := 1 and Set BLAS := mkl in Makefile.config

- make all -j 36

- run my tests

Then I got the test result as listed in previous reply. 

After check the codes, I found the info of "Total number of sockets: 2" only shows up when _OPENMP is enable. Looks like the following setting in Makefile.config is not working??? May need to check for this?
        `# Uncomment to disable OpenMP support.`
        `# USE_OPENMP := 0`

So I tried to build caffe via cmake,

- cmake -DCPU_ONLY=ON -DUSE_OPENMP=ON -DBLAS=mkl ..

Finally, I got the similar performance as yours.
I0317 17:41:26.582989 60986 caffe.cpp:479] Average Forward pass: 355.05 ms.
I0317 17:41:26.582993 60986 caffe.cpp:481] Average Backward pass: 905.575 ms.
I0317 17:41:26.582998 60986 caffe.cpp:483] Average Forward-Backward: 1260.65 ms.
I0317 17:41:26.583003 60986 caffe.cpp:485] Total Time: 25213 ms.

 Thanks again for your help! :)

Best Regards,
Chency

**Comment by jczaja** [comment]
Glad to hear that intelcaffe worked for You. But it seems that GCC has OpenMP support it just OpenMP makefile based detection fails , so If this is not a problem please share with us output of following steps:
* _make clean_
* _source /opt/intel/mkl/bin/mklvars.sh intel64_
* _cp Makefile.config.example Makefile.config_
* uncomment CPU_ONLY := 1 and Set BLAS := mkl in Makefile.config
* _make all test -n_

This would help us to fix OpenMP detection in makefiles.

Best Regards,
Jacek

**Comment by ciychen** [comment]
Hi Jacek,

Here's the output after your steps, didn't find OpenMP enabled during building process.
[intelcaffe_log.txt](https://github.com/intelcaffe/caffe/files/178928/intelcaffe_log.txt)

Best Regards,
Chency

**Comment by jczaja** [comment]
I looked at your attached log, but did not get any clue what is wrong, so I would like to ask you to perform similar test if possible. In Makefile (line 446:471) there is an mechanism of detection if compiler used for building caffe is supporting OpenMP. Error that happens during that test are discarded eg. 2>/dev/null . I would like you to edit Makefile in a following way:
* remove _2>/dev/null_ from line 452 of Makefile
* remove _2>/dev/null_ from line 459 of Makefile

and then perform test as before eg.

* make clean
* source /opt/intel/mkl/bin/mklvars.sh intel64
* cp Makefile.config.example Makefile.config
* uncomment CPU_ONLY := 1 and Set BLAS := mkl in Makefile.config
* make all test -n

Then if you could please record and share log again with us.

Best Regards,
Jacek

**Comment by ciychen** [comment]
Hi Jacek,

Please check the log from file  
[build_log.txt](https://github.com/intelcaffe/caffe/files/181884/build_log.txt).

The make application on my machine is: GNU Make 3.81

I have two question regarding the alexnet benchmark used in your performance results (1257ms)

1. Is your AlexNet prototype using/enabling "norm" layer?
2. What's the value of group number in your AlexNet prototype?
I appreciate if you can send me the full test log of alexnet on intelcaffe :) 


Best Regards,
Chency

**Comment by intelmm** [comment]
Hi Chency,

Thank you very much for your help.
The log you sent was very useful for us.

Regarding your questions:
1. if you mean `norm1` and `norm2` LRN layers, yes it uses this type of layer.
2. caffe test requires some weights, however we are just using following command to collect performance results:

```
./build/tools/caffe time --model=models/bvlc_alexnet/train_val.prototxt
```

Where file `train_val.prototxt` is available [here](https://github.com/intelcaffe/caffe/blob/master/models/bvlc_alexnet/train_val.prototxt).
Example outputs from above command execution has been attached [here](https://github.com/intelcaffe/caffe/files/182176/alexnet_out.txt).

Best Regards,
Mariusz

**Comment by ciychen** [comment]
Hi  Mariusz,

Thanks for your information.

There's one difference (Number of OpenMP threads) in my outputs compared with yours when running models/bvlc_alexnet/train_val.prototxt:
mine:
I0322 12:35:14.481976 69000 caffe.cpp:414] Use CPU.
I0322 12:35:14.498358 69000 cpu_info.cpp:340] Total number of sockets: 2
I0322 12:35:14.498414 69000 cpu_info.cpp:343] Total number of CPU cores: 36
I0322 12:35:14.498424 69000 cpu_info.cpp:346] Total number of processors: 36
I0322 12:35:14.498431 69000 cpu_info.cpp:349] GPU is used: no
I0322 12:35:14.498448 69000 cpu_info.cpp:352] OpenMP environmental variables are specified: no
I0322 12:35:14.498456 69000 cpu_info.cpp:355] OpenMP thread bind allowed: yes
I0322 12:35:14.498468 69000 cpu_info.cpp:358] Number of OpenMP threads: 34

yours:
I0321 13:03:13.984489 10495 caffe.cpp:414] Use CPU.
I0321 13:03:14.002429 10495 cpu_info.cpp:340] Total number of sockets: 2
I0321 13:03:14.002473 10495 cpu_info.cpp:343] Total number of CPU cores: 36
I0321 13:03:14.002508 10495 cpu_info.cpp:346] Total number of processors: 36
I0321 13:03:14.002521 10495 cpu_info.cpp:349] GPU is used: no
I0321 13:03:14.002552 10495 cpu_info.cpp:352] OpenMP environmental variables are specified: no
I0321 13:03:14.002563 10495 cpu_info.cpp:355] OpenMP thread bind allowed: yes
I0321 13:03:14.002578 10495 cpu_info.cpp:358] Number of OpenMP threads: 35

I haven't set any export (OMP_NUM_THREADS) before running caffe time. Since intelcaffe
tries to determine on its own number of OpenMP threads to be used, how can the number be different in my case?


Best Regards,
Chency

**Comment by intelmm** [comment]
Hi Chency,

You are right. The number of OpenMP threads used by intelcaffe has been temporary reduced to 34. It will be restored within few days.

If you would like to use all 35 OpenMP threads, change following lines in file /src/caffe/util/cpu_info.cpp:
```
223: logicalCoreId += 1;
...
314: omp_set_num_threads(totalNumberOfAvailableCores - 1);
```

Best Regards,
Mariusz
