### ISSUE TITLE
Any trick to make "engine: MKL2017" work?

### ISSUE THREAD

**Issue by sato-cloudian** [intelcaffe/caffe#10]
Hi,

I have tried **engine: MKL2017** to get further boost in my NIN networks and in another of alexnet.

But for some reasons, their outputs got stack as below, and their cpus stayed around 1600%(16 physical cores each). I have waited for almost an hour, and terminated.

> ...
> I0518 10:45:02.950623 21880 net.cpp:236] data does not need backward computation.
> I0518 10:45:02.950630 21880 net.cpp:278] This network produces output accuracy
> I0518 10:45:02.950639 21880 net.cpp:278] This network produces output accuracy3
> I0518 10:45:02.950670 21880 net.cpp:292] Network initialization done.
> I0518 10:45:02.950858 21880 solver.cpp:62] Solver scaffolding done.
> I0518 10:45:02.950968 21880 caffe.cpp:262] Starting Optimization
> I0518 10:45:02.950978 21880 solver.cpp:292] Solving cars_finegrained_nin
> I0518 10:45:02.950985 21880 solver.cpp:293] Learning Rate Policy: step
> I0518 10:45:02.950994 21880 solver.cpp:350] Iteration 0, Testing net (#0)
> I0518 10:45:02.951619 21880 net.cpp:703] Ignoring source layer loss
> ^C

Tried several times, but wasn't able to make it work.

For the alexnet, there are only two differences.

1. train/val data pointed to my own lmdb locations
* images are 1x256x256(gray)
2. num_output of fc8 changed to 337 for my own samples

My environment is as follows:

**intelcaffe**

> $ git show
> commit 8ca6c17896836e7ea6556e5161b385c70e57f309
> Merge: 601489b e3a6e56
> Author: Jacek Czaja <jacek.czaja@intel.com>
> Date:   Thu May 12 11:50:29 2016 +0200
> 
>     task-mt-transform-fix: - Fix to multihthreaded transform code

**OS**

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 14.04.3 LTS
> Release: 14.04
> Codename: trusty

**MKL**

> $ env | grep MKL
> MKLROOT=/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl
> MKL_CBWR=AUTO

**CPU**

> processor : 31
> vendor_id : GenuineIntel
> cpu family : 6
> model : 63
> model name : Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
> stepping : 2
> microcode : 0x31
> cpu MHz : 1202.062
> cache size : 20480 KB
> physical id : 1
> siblings : 16
> core id : 7
> cpu cores : 8
> apicid : 31
> initial apicid : 31
> fpu : yes
> fpu_exception : yes
> cpuid level : 15
> wp : yes
> flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs :
> bogomips : 4789.84
> clflush size : 64
> cache_alignment : 64
> address sizes : 46 bits physical, 48 bits virtual
> power management:

**Comment by jreniecki** [comment]
Hi,
We just pushed a bunch of changes. Could you try again with the latest revision? If problem persists we will take a closer look.
Thanks!

**Comment by sato-cloudian** [comment]
Wow. Thanks for those updates.

I have tried with the latest build, but still see the same behaviour, stucked(actually running at 1600%) at the 1st Test.

My network definition with MKL2017 is [here at gist](https://gist.github.com/sato-cloudian/f847aef1c75528c9b41a213832a26306).

Thanks.

**Comment by jreniecki** [comment]
Hello,
Thanks for confirming this. I'll try to run your topology and will get back to you when I have some feedback.
Please note that the MKL2017 engine based on 'MKL2017 Beta' release is a very early version. By the end of next week 'MKL2017 Beta Update1  version will be available which will have many bug fixes and  performance improvements. I'll let you know if the fix for your problem is included in the update.

Thanks!

**Comment by sato-cloudian** [comment]
I see, thanks!

Could you tell what is the supported configuration of MKL2017 for now? My try on alexnet had only two minor differences on the input channel(gray scale) and the output size(337 instead of 1000). 

Also, just for confirmation, I don't need to set "engine" parameter to get the performance boost as described in README of intelcaffe, correct?

**Comment by jreniecki** [comment]
Correct. The results in README come from tests without using MKL2017 engine.

**Comment by jreniecki** [comment]
> My try on alexnet had only two minor differences on the input channel(gray scale) and the output size(337 instead of 1000).

I noticed more differences than you described. First of all, your conv1 has a kernel_size 32 instead of 11. This is the change that most significantly impacts the performance. If you want to keep using this topology I'll ask MKL team for support.

**Comment by sato-cloudian** [comment]
Thanks for taking a look at my network.

The network on gist is not alexnet, but NIN. So yes, there are significant differences.

But I have tried alexnet as well. Here's [the details](https://gist.github.com/sato-cloudian/4b288a95e4f02514fb2a0b348d28613a).

As you can see, mkl2017_alexnet without engine parameters ran 4.5 times faster(avg time on 10 iterations, about 3 mins with engine parameters, about 40 secs without engine parameters).

I have tried disabling hyper threading, but which didn't make any difference. Also tried environmental variables [as described in the past](https://software.intel.com/en-us/articles/single-node-caffe-scoring-and-training-on-intel-xeon-e5-series-processors), but which again didn't make any difference.

Do I need to set any particular environmental variables on MKL or somewhere?

**Comment by jreniecki** [comment]
I ran some tests and in my experience mkl2017 engine should be about 30% faster than the default engine, but I tested on database of color images...
One helpful tool is "caffe time" which will tell you which layer performs badly. This is how you start it:
`build/tools/caffe time -model models/mkl2017_alexnet/train_val.prototxt -iterations 50`

If first convolution turns out to be problematic then it would suggest that problem is caused by number of input channels. If you could try to test on both color and gray-scale images then we would know for sure. (Sorry, I don't have any gray-scale images to use for testing.)

**Comment by sato-cloudian** [comment]
Hi,

I have confirmed up to 100 images/sec at trainings both for color and gray ones!

Thanks!!
