### ISSUE TITLE
using engine: mkl2017 is hurting performance

### ISSUE THREAD

**Issue by jeffdaily** [intelcaffe/caffe#14]
I have installed the latest checkout of intelcaffe. c9cbbfbe3ffeedc4c12896657866a6cbdac45617

- gcc 4.8.2
- mkl 2017 beta update 1

lscpu output:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               1300.000
BogoMIPS:              5599.15
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
NUMA node1 CPU(s):     10-19
```

I'm running the benchmarks from your README.md, but since I'm impatient I'm only running 10 iterations.  I also have installed BVLC caffe using mkl2017 beta update 1 so I can compare the performance of it versus intelcaffe.  

BVLC caffe and intelcaffe alexnet are run like so `./build/tools/caffe time -model=models/bvlc_alexnet/train_val.prototxt -iterations 10`

intelcaffe mkl2017 alexnet is run like so `./build/tools/caffe time --model=models/mkl2017_alexnet/train_val.prototxt -iterations 10

Results are as follows:

    | BVLC caffe | intelcaffe | intelcaffe mkl2017_alexnet
--- | -------------- | ----------- | ----------------------------------
| Average Forward-Backward: | 3931.3 ms. | 9992.7 ms | 328133.0 

The mkl2017_alexnet is extremely slow.  Please correct my understanding, but unless I use the "engine: mkl2017" prototxt attribute, then I'm only using non-specific intel improvements to caffe and *not* MKL2017 DNN primitives?  Why is it then when I enable the MKL DNN primitives that performance tanks?  Am I doing something wrong?

**Comment by jeffdaily** [comment]
Here is a layer by layer breakdown using intelcaffe with and without engine mkl2017.   Something clearly isn't right since using engine mkl2017 is drastically hurting performance.  I sincerely hope this is user error (as it usually is).

| layer | direction | engine: mkl2017 | intelcaffe | diff       | 
|-------|-----------|-----------------|------------|------------| 
| data  | forward:  | 59.127          | 44.706     | 14.421     | 
| data  | backward: | 0.002           | 0.001      | 0.001      | 
| conv1 | forward:  | 5442.36         | 342.53     | 5099.83    | 
| conv1 | backward: | 24034           | 188.135    | 23845.865  | 
| relu1 | forward:  | 28.149          | 27.387     | 0.762      | 
| relu1 | backward: | 33.733          | 34.041     | -0.308     | 
| norm1 | forward:  | 348.033         | 148.736    | 199.297    | 
| norm1 | backward: | 2103.93         | 170.479    | 1933.451   | 
| pool1 | forward:  | 32.904          | 31.027     | 1.877      | 
| pool1 | backward: | 50.874          | 50.895     | -0.021     | 
| conv2 | forward:  | 10895.5         | 311.226    | 10584.274  | 
| conv2 | backward: | 104774          | 808.763    | 103965.237 | 
| relu2 | forward:  | 17.829          | 13.975     | 3.854      | 
| relu2 | backward: | 21.399          | 21.421     | -0.022     | 
| norm2 | forward:  | 232.365         | 86.242     | 146.123    | 
| norm2 | backward: | 1515.62         | 93.942     | 1421.678   | 
| pool2 | forward:  | 21.645          | 19.268     | 2.377      | 
| pool2 | backward: | 32.334          | 32.578     | -0.244     | 
| conv3 | forward:  | 9772.95         | 117.698    | 9655.252   | 
| conv3 | backward: | 71032.3         | 344.702    | 70687.598  | 
| relu3 | forward:  | 4.476           | 4.208      | 0.268      | 
| relu3 | backward: | 6.379           | 7.01       | -0.631     | 
| conv4 | forward:  | 5929.96         | 107.176    | 5822.784   | 
| conv4 | backward: | 52834.6         | 338.62     | 52495.98   | 
| relu4 | forward:  | 4.537           | 4.252      | 0.285      | 
| relu4 | backward: | 6.389           | 7.236      | -0.847     | 
| conv5 | forward:  | 4073.28         | 80.005     | 3993.275   | 
| conv5 | backward: | 35256.9         | 263.255    | 34993.645  | 
| relu5 | forward:  | 1.934           | 2.59       | -0.656     | 
| relu5 | backward: | 4.495           | 4.631      | -0.136     | 
| pool5 | forward:  | 4.96            | 4.621      | 0.339      | 
| pool5 | backward: | 5.482           | 5.067      | 0.415      | 
| fc6   | forward:  | 35.889          | 35.531     | 0.358      | 
| fc6   | backward: | 57.459          | 56.485     | 0.974      | 
| relu6 | forward:  | 0.252           | 0.255      | -0.003     | 
| relu6 | backward: | 0.201           | 0.192      | 0.009      | 
| drop6 | forward:  | 0.37            | 0.372      | -0.002     | 
| drop6 | backward: | 0.364           | 0.344      | 0.02       | 
| fc7   | forward:  | 16.016          | 16.161     | -0.145     | 
| fc7   | backward: | 31.195          | 29.528     | 1.667      | 
| relu7 | forward:  | 0.243           | 0.246      | -0.003     | 
| relu7 | backward: | 0.195           | 0.201      | -0.006     | 
| drop7 | forward:  | 0.363           | 0.377      | -0.014     | 
| drop7 | backward: | 0.357           | 0.385      | -0.028     | 
| fc8   | forward:  | 3.908           | 3.952      | -0.044     | 
| fc8   | backward: | 8.433           | 8.039      | 0.394      | 
| loss  | forward:  | 0.943           | 0.767      | 0.176      | 
| loss  | backward: | 0.226           | 0.214      | 0.012      |

**Comment by jreniecki** [comment]
Hello,
I'm sorry, but your CPU seems to be based on the Ivy Bridge architecture, so it's lacking AVX-2 instruction set.
The performance improvements that are included in the Intelcaffe fork are currently tested on Intel Xeon E3/E5 v3 series only and the optimized primitives included in MKL2017 Beta rely on AVX-2 instructions.

I apologize for the inconvenience.

**Comment by jeffdaily** [comment]
Thank you for clearing this up.  Closing this issue.
