### ISSUE TITLE
USE_MKL option not working

### ISSUE THREAD

**Issue by awan-10** [intelcaffe/caffe#16]
I have downloaded MKL-DNN and MKL-2017 from Intel website and built Intel-Caffe with MKL2017 but I still get an error when I run. 

./build/tools/caffe train -solver models/mkl2017_alexnet/solver.prototxt

In my Makefile.config, I have added these and everything compiles fine but running throws the error I have pasted at the end.

CPU_ONLY := 1
USE_MKL2017_AS_DEFAULT_ENGINE := 1

I0703 08:01:20.309558 27019 layer_factory.hpp:77] Creating layer conv1
F0703 08:01:20.309579 27019 layer_factory.cpp:82] Layer conv1 has unknown engine.
*** Check failure stack trace: ***
    @     0x7fb4fa552d0d  google::LogMessage::Fail()
    @     0x7fb4fa5580ba  google::LogMessage::SendToLog()
    @     0x7fb4fa554de0  google::LogMessage::Flush()
    @     0x7fb4fa5550cd  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb4faaba643  caffe::GetConvolutionLayer<>()
    @     0x7fb4fa9de447  caffe::LayerRegistry<>::CreateLayer()
    @     0x7fb4faaaf8a4  caffe::Net<>::Init()
    @     0x7fb4faab19d5  caffe::Net<>::Net()
    @     0x7fb4fa9a949a  caffe::Solver<>::InitTrainNet()
    @     0x7fb4fa9aa3cc  caffe::Solver<>::Init()
    @     0x7fb4fa9aa758  caffe::Solver<>::Solver()
    @     0x7fb4fa9bb0b3  caffe::Creator_SGDSolver<>()
    @     0x7fb4fafb568d  caffe::SolverRegistry<>::CreateSolver()
    @     0x7fb4fafae7e8  train()
    @     0x7fb4fafabd46  main
    @     0x7fb4f788cb15  __libc_start_main
    @     0x7fb4fafac671  (unknown)
Aborted (core dumped)

**Comment by jreniecki** [comment]
Hi,
Make sure that you set
`BLAS := mkl`
in your Makefile.config

Also, remember to set environment variables for MKL before compiling. You can do it by typing:
`source /opt/intel/mkl/bin/mklvars.sh intel64`

**Comment by awan-10** [comment]
Thank you @jreniecki. I had the BLAS := mkl already but was missing the source line step. It works now!
