### ISSUE TITLE
make runtest fails

### ISSUE THREAD

**Issue by sato-cloudian** [intelcaffe/caffe#4]
Hi,

Thanks for pushing lots of changes.

I tried the latest intelcaffe and MKL, but _make runtest_ failed as follows:

> [----------] Global test environment tear-down
> [==========] 1050 tests from 146 test cases ran. (41776 ms total)
> [  PASSED  ] 1046 tests.
> [  FAILED  ] 4 tests, listed below:
> [  FAILED  ] DataLayerTest/0.TestReadLMDB, where TypeParam = caffe::CPUDevice<float>
> [  FAILED  ] DataLayerTest/0.TestReadLevelDB, where TypeParam = caffe::CPUDevice<float>
> [  FAILED  ] DataLayerTest/1.TestReadLevelDB, where TypeParam = caffe::CPUDevice<double>
> [  FAILED  ] DataLayerTest/1.TestReadLMDB, where TypeParam = caffe::CPUDevice<double>
> 
>  4 FAILED TESTS
>   YOU HAVE 4 DISABLED TESTS
> 
> make: *** [runtest] Error 1

My environments are:

**intelcaffe**

> $ git show
> commit 601489bb3d8f7b1526c1aa18a2409558bc0bc70f
> Merge: f69e312 a4a9229
> Author: Jacek Czaja <jacek.czaja@intel.com>
> Date:   Mon May 9 08:24:31 2016 +0200
> 
>     task-transform-optimizations:  Improvments to Transform PART 1
> 

**MKL**

> $ env | grep MKL
> MKLROOT=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl
(l_mkl_11.3.3.210)

**OS**

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.3 LTS
> Release:	14.04
> Codename:	trusty

**CPU**

> processor	: 31
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 63
> model name	: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
> stepping	: 2
> microcode	: 0x31
> cpu MHz		: 1202.062
> cache size	: 20480 KB
> physical id	: 1
> siblings	: 16
> core id		: 7
> cpu cores	: 8
> apicid		: 31
> initial apicid	: 31
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 15
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
> bugs		:
> bogomips	: 4789.84
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 46 bits physical, 48 bits virtual
> power management:

I tried an older version of MKL(l_mkl_11.3.3.210), but got the same error.

Also, I confirmed BVLC works fine on the same box.

Thanks

**Comment by sato-cloudian** [comment]
> I tried an older version of MKL(l_mkl_11.3.3.210), but got the same error.

Please read the version as l_mkl_11.3.2.181.

**Comment by jczaja** [comment]
Hi,

Thanks for looking at intelcaffe. We just reproduced that problem (There is some thread racing I'm assuming that makes problem manifesting itself not each time we run the tests). We are working on issue. As soon as we have it fixed I will let you know. Meantime please use previous revision.

Thanks for your report.

**Comment by jczaja** [comment]
@sato-cloudian We just made a fix, that should even out the issue You reported. Please sync with most recent revision and write us if issue is still present

**Comment by sato-cloudian** [comment]
Great, thanks. I confirmed it works as below.

> $ git show
> commit 8ca6c17896836e7ea6556e5161b385c70e57f309
> Merge: 601489b e3a6e56
> Author: Jacek Czaja <jacek.czaja@intel.com>
> Date:   Thu May 12 11:50:29 2016 +0200
> 
>     task-mt-transform-fix: - Fix to multihthreaded transform code
> 

**result**

> [----------] Global test environment tear-down
> [==========] 1050 tests from 146 test cases ran. (41073 ms total)
> [  PASSED  ] 1050 tests.
