### ISSUE TITLE
intelcaffe supports MKL 2017 Beta?

### ISSUE THREAD

**Issue by sato-cloudian** [intelcaffe/caffe#8]
Hi,

I tried to build intelcaffe with MKL 2017 Beta, but failed with the following errors.

If possible, I want to try both to accelerate our deep learning projects. So let me know if intelcaffe supports the beta anytime soon.

The build with BVLC caffe worked fine.

**ERROR**

> ...
> CXX src/caffe/multinode/SynchronousParamClient.cpp
> CXX src/caffe/multinode/BlobKeyChain.cpp
> CXX src/caffe/multinode/DataServer.cpp
> AR -o .build_release/lib/libcaffe.a
> LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
> CXX tools/train_net.cpp
> CXX/LD -o .build_release/tools/train_net.bin
> CXX tools/upgrade_net_proto_binary.cpp
> CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
> .build_release/lib/libcaffe.so: undefined reference to `dnnLRNCreateForward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLRNCreateBackward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutDelete_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLRNCreateBackward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnPoolingCreateForward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnAllocateBuffer_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnDelete_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardData_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCreate_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReLUCreateBackward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnPoolingCreateForward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutDelete_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutGetMemorySize_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnExecute_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateForward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnPoolingCreateBackward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReLUCreateForward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardBias_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnConversionCreate_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCompare_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLRNCreateForward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateForward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateForwardBias_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardFilter_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnExecute_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardFilter_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardBias_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReleaseBuffer_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReleaseBuffer_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCompare_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnDelete_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCreate_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateBackwardData_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnAllocateBuffer_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnGroupsConvolutionCreateForwardBias_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCreateFromPrimitive_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutCreateFromPrimitive_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnConversionCreate_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReLUCreateBackward_F32'
> .build_release/lib/libcaffe.so: undefined reference to `dnnLayoutGetMemorySize_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnPoolingCreateBackward_F64'
> .build_release/lib/libcaffe.so: undefined reference to `dnnReLUCreateForward_F32'
> collect2: error: ld returned 1 exit status
> make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1 

**MKL**

> $ env | grep MKL
> MKLROOT=/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl

My environment is the same as the issue #4.

Thanks.

**Comment by jreniecki** [comment]
This could happen if you have two different MKL versions installed and your variables such as LD_LIBRARY_PATH point to different locations. Do you use CMake or Makefile to build caffe? Try also checking: 
env | grep mkl

(mkl with small letters)

**Comment by sato-cloudian** [comment]
OK, it looks like there's no multiple entries.

> $ env | grep mil
> MKLROOT=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl
> LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/tbb/lib/intel64/gcc4.4:/opt/intel/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64
> MIC_LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/tbb/lib/mic::/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/mic
> LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/tbb/lib/intel64/gcc4.4:/opt/intel/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64:/home/tsato/anaconda2/lib
> CPATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/include
> NLSPATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64/locale/%l_%t/%N

But anyway, I will try uninstalling the existing version, and another build after reinstalling the beta.

**Comment by sato-cloudian** [comment]
> OK, it looks like there's no multiple entries.

Ignore my previous comment. It was on 2016.3.210 env.

I have uninstalled MKL 2016.3.210 and MKL 2017 beta, 
then reinstalled MKL 2017 beta.

Environmental variables are as follows.

> $ env | grep mil
> MKLROOT=/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl
> LIBRARY_PATH=/opt/intel/compilers_and_libraries_2017.0.042/linux/tbb/lib/intel64/gcc4.4:/opt/intel/compilers_and_libraries_2017.0.042/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl/lib/intel64
> MIC_LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2017.0.042/linux/tbb/lib/mic:/opt/intel/compilers_and_libraries_2017.0.042/linux/compiler/lib/mic:/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl/lib/mic
> LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2017.0.042/linux/tbb/lib/intel64/gcc4.4:/opt/intel/compilers_and_libraries_2017.0.042/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl/lib/intel64
> CPATH=/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl/include
> NLSPATH=/opt/intel/compilers_and_libraries_2017.0.042/linux/mkl/lib/intel64/locale/%l_%t/%N

The installation folder looks like this.

> $ ls -l /opt/intel/
> total 104
> lrwxrwxrwx  1 root root    35  5月 16 09:20 advisor -> /opt/intel//advisor_2017.0.0.457467
> lrwxrwxrwx  1 root root    35  5月 16 09:20 advisor_2017 -> /opt/intel//advisor_2017.0.0.457467
> drwxr-xr-x 16 root root  4096  5月 16 09:20 advisor_2017.0.0.457467
> drwxr-xr-x  2 root root  4096  5月 16 09:22 bin
> drwxr-xr-x  3 root root  4096  5月 16 09:19 clck
> lrwxrwxrwx  1 root root    27  5月 16 09:22 clck_latest -> /opt/intel//clck/2017.0.006
> lrwxrwxrwx  1 root root    28  5月 16 09:22 compilers_and_libraries -> compilers_and_libraries_2017
> drwxr-xr-x  3 root root  4096  5月 16 09:22 compilers_and_libraries_2017
> drwxr-xr-x  4 root root  4096  5月 16 09:22 compilers_and_libraries_2017.0.042
> lrwxrwxrwx  1 root root    34  5月 16 09:22 daal -> compilers_and_libraries/linux/daal
> drwxr-xr-x  8 root root  4096  5月 16 09:22 debugger_2017
> drwxr-xr-x  3 root root  4096  5月 16 09:22 documentation_2017
> drwxr-xr-x  3 root root  4096  5月 16 09:22 ide_support_2017
> drwxr-xr-x  2 root root  4096  5月 16 09:21 imp
> drwxr-xr-x  2 root root  4096  5月 16 09:21 impi
> lrwxrwxrwx  1 root root    37  5月 16 09:22 include -> compilers_and_libraries/linux/include
> lrwxrwxrwx  1 root root    37  5月 16 09:20 inspector -> /opt/intel//inspector_2017.0.0.456840
> lrwxrwxrwx  1 root root    37  5月 16 09:20 inspector_2017 -> /opt/intel//inspector_2017.0.0.456840
> drwxr-xr-x 16 root root  4096  5月 16 09:20 inspector_2017.0.0.456840
> -rw-r--r--  1 root root 21843  5月 16 09:22 intel_sdp_products.db
> -rw-r--r--  1 root root   108  5月 12 11:32 intel_sdp_products.tgz.db
> lrwxrwxrwx  1 root root    33  5月 16 09:22 ipp -> compilers_and_libraries/linux/ipp
> drwxr-xr-x  8 root root  4096  5月 12 11:32 ism
> drwxr-xr-x  3 root root  4096  5月 16 09:19 italic
> lrwxrwxrwx  1 root root    26  5月 16 09:22 itac_2017 -> /opt/intel/itac/2017.0.009
> lrwxrwxrwx  1 root root    27  5月 16 09:22 itac_latest -> /opt/intel//itac/2017.0.009
> lrwxrwxrwx  1 root root    33  5月 16 09:22 lib -> compilers_and_libraries/linux/lib
> drwxr-xr-x  2 root root  4096  5月 12 11:10 licenses
> lrwxrwxrwx  1 root root    33  5月 16 09:22 man -> compilers_and_libraries/linux/man
> lrwxrwxrwx  1 root root    33  5月 16 09:22 mkl -> compilers_and_libraries/linux/mkl
> drwxr-xr-x  6 root root  4096  5月 16 09:22 parallel_studio_xe_2017.0.014
> lrwxrwxrwx  1 root root    88  5月 16 09:19 performance_snapshot -> /opt/intel//vtune_amplifier_xe_2017.0.0.457868/documentation/en/performance_snapshot.htm
> drwxr-xr-x  3 root root  4096  5月 16 09:22 samples_2017
> lrwxrwxrwx  1 root root    33  5月 16 09:22 tbb -> compilers_and_libraries/linux/tbb
> lrwxrwxrwx  1 root root    46  5月 16 09:19 vtune_amplifier_xe -> /opt/intel//vtune_amplifier_xe_2017.0.0.457868
> lrwxrwxrwx  1 root root    46  5月 16 09:19 vtune_amplifier_xe_2017 -> /opt/intel//vtune_amplifier_xe_2017.0.0.457868
> drwxr-xr-x 23 root root  4096  5月 16 09:20 vtune_amplifier_xe_2017.0.0.457868

Again, BVLC caffe got built successfully, but intelcaffe failed by the same errors.

**Comment by sato-cloudian** [comment]
I have installed MKL only from Parallel Studio 2017 Beta. But do I need any other components to build intelcaffe?

**Comment by jreniecki** [comment]
Hi,
Everything seems OK, I have no idea why the linking fails.
If you are using Makefiles, could you uncomment the last line in Makefile.config and send me your compilation log? (If you're using CMake, then something like  ' make VERBOSE=1' should give the same results)

**Comment by sato-cloudian** [comment]
Hi, thanks for checking my issue. 

Then, the beta is supposed to work with intelcaffe?

I followed your instruction, and made [a public gist of compilation log](https://gist.github.com/sato-cloudian/5bd27863b75a9f47b87b6ef954afcdc0).

**Comment by jreniecki** [comment]
Yes, it should and it is working for many people including myself :)
It's weird, all the paths look good in your log, but somehow your linker seems to be trying to link libcaffe.so with some older version of MKL...
In MKL2017 there are new dnn primitives and as you can see, despite the fact that you have MKL2017 beta installed, the dnn primitives cannot be found by the linker. 

Now I suspect that anaconda package contains the older version of MKL shared library. Could you try to check if somewhere in your /home/tsato/anaconda2/lib directory there is a file named mkl_rt.so ?

**Comment by jreniecki** [comment]
I installed anaconda and I found mkl library in anaconda2/lib directory...
That's the problem. Header files are taken from mkl2017beta, but the libmkl_rt.so file is linked from anaconda2/lib location.

Quick work-around would be to remove or rename anaconda2/lib/libmkl_rt.so  file....

**Comment by sato-cloudian** [comment]
Thanks for clarifying! Yes, I became able to compile without any errors!!

The library below was on my box. But do you have any idea who had put this?? Is this included in anaconda itself?

> $ ls -l anaconda2/lib/libmkl_rt.so
> -rwxrwxr-x 2 tsato tsato 5147301  1月 12 13:45 anaconda2/lib/libmkl_rt.so

**Comment by jreniecki** [comment]
Yes, the anaconda installer contains some version of MKL apparently... (and many other libraries)
https://www.continuum.io/blog/developer/mkl-optimizations-anaconda

**Comment by sato-cloudian** [comment]
Oh, I see, thanks. For the time being, this issue would help others who have a problem like mine.
