### ISSUE TITLE
some types are not declared

### ISSUE THREAD

**Issue by sato-cloudian** [intelcaffe/caffe#9]
Hi,

Thanks for pushing some more changes, especially, I appreciate average support in pooling since I use NIN on our project.

But some types are missing as _make all_ fails as follows!

> CXX src/caffe/layers/mkl_batch_norm_layer.cpp
> In file included from ./include/caffe/layers/mkl_layers.hpp:15:0,
>                  from src/caffe/layers/mkl_batch_norm_layer.cpp:6:
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnConcatCreate(void**, dnnPrimitiveAttributes_t, size_t, void**) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:651:12: error: ‘dnnConcatCreate_F32’ was not declared in this scope
>          src);}
>             ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnConcatCreate(void**, dnnPrimitiveAttributes_t, size_t, void**) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:661:12: error: ‘dnnConcatCreate_F64’ was not declared in this scope
>          src);}
>             ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnSplitCreate(void**, dnnPrimitiveAttributes_t, size_t, dnnLayout_t, size_t*) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:681:12: error: ‘dnnSplitCreate_F32’ was not declared in this scope
>          dst);}
>             ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnSplitCreate(void**, dnnPrimitiveAttributes_t, size_t, dnnLayout_t, size_t*) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:693:12: error: ‘dnnSplitCreate_F64’ was not declared in this scope
>          dst);}
>             ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnSumCreate(void**, dnnPrimitiveAttributes_t, size_t, dnnLayout_t, Dtype*) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:707:29: error: ‘dnnSumCreate_F32’ was not declared in this scope
>          layout, coefficients);}
>                              ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnSumCreate(void**, dnnPrimitiveAttributes_t, size_t, dnnLayout_t, Dtype*) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; size_t = long unsigned int; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:716:29: error: ‘dnnSumCreate_F64’ was not declared in this scope
>          layout, coefficients);}
>                              ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateForward(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:729:24: error: ‘dnnBatchNormalizationCreateForward_F32’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateForward(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:737:24: error: ‘dnnBatchNormalizationCreateForward_F64’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardData(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:751:24: error: ‘dnnBatchNormalizationCreateBackwardData_F32’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardData(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:760:24: error: ‘dnnBatchNormalizationCreateBackwardData_F64’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardScaleShift(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:773:24: error: ‘dnnBatchNormalizationCreateBackwardScaleShift_F32’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardScaleShift(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:781:24: error: ‘dnnBatchNormalizationCreateBackwardScaleShift_F64’ was not declared in this scope
>          dataLayout, eps); }
>                         ^
> src/caffe/layers/mkl_batch_norm_layer.cpp: In member function ‘virtual void caffe::MKLBatchNormLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
> src/caffe/layers/mkl_batch_norm_layer.cpp:170:45: error: ‘dnnResourceScaleShift’ was not declared in this scope
>          &scaleShift_buffer_l, batchNormFwd, dnnResourceScaleShift);
>                                              ^
> src/caffe/layers/mkl_batch_norm_layer.cpp:199:17: error: ‘dnnResourceScaleShift’ was not declared in this scope
>    BatchNorm_res[dnnResourceScaleShift] = scaleShift_buffer_;
>                  ^
> src/caffe/layers/mkl_batch_norm_layer.cpp: In member function ‘virtual void caffe::MKLBatchNormLayer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’:
> src/caffe/layers/mkl_batch_norm_layer.cpp:270:17: error: ‘dnnResourceScaleShift’ was not declared in this scope
>    BatchNorm_res[dnnResourceScaleShift] = scaleShift_buffer_;
>                  ^
> src/caffe/layers/mkl_batch_norm_layer.cpp:281:32: error: ‘dnnResourceDiffScaleShift’ was not declared in this scope
>      BatchNormBwdScaleShift_res[dnnResourceDiffScaleShift] = scaleShift_buffer_;
>                                 ^
> src/caffe/layers/mkl_batch_norm_layer.cpp: In instantiation of ‘void caffe::MKLBatchNormLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
> src/caffe/layers/mkl_batch_norm_layer.cpp:310:1:   required from here
> src/caffe/layers/mkl_batch_norm_layer.cpp:85:14: warning: unused variable ‘data’ [-Wunused-variable]
>        Dtype* data = this->blobs_[1]->mutable_cpu_data();
>               ^
> src/caffe/layers/mkl_batch_norm_layer.cpp:73:12: warning: unused variable ‘data’ [-Wunused-variable]
>      Dtype* data = this->blobs_[0]->mutable_cpu_data();
>             ^
> src/caffe/layers/mkl_batch_norm_layer.cpp: In instantiation of ‘void caffe::MKLBatchNormLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
> src/caffe/layers/mkl_batch_norm_layer.cpp:310:1:   required from here
> src/caffe/layers/mkl_batch_norm_layer.cpp:85:14: warning: unused variable ‘data’ [-Wunused-variable]
>        Dtype* data = this->blobs_[1]->mutable_cpu_data();
>               ^
> src/caffe/layers/mkl_batch_norm_layer.cpp:73:12: warning: unused variable ‘data’ [-Wunused-variable]
>      Dtype* data = this->blobs_[0]->mutable_cpu_data();
>             ^
> In file included from ./include/caffe/layers/mkl_layers.hpp:15:0,
>                  from src/caffe/layers/mkl_batch_norm_layer.cpp:6:
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateForward(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:729:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardData(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:751:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardScaleShift(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = float; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:773:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateForward(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:737:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardData(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:760:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> ./include/mkl_dnn_cppwrapper.h: In function ‘dnnError_t dnnBatchNormalizationCreateBackwardScaleShift(void**, dnnPrimitiveAttributes_t, dnnLayout_t, float) [with Dtype = double; dnnPrimitive_t = void*; dnnPrimitiveAttributes_t = void*; dnnLayout_t = void*]’:
> ./include/mkl_dnn_cppwrapper.h:781:27: warning: control reaches end of non-void function [-Wreturn-type]
>          dataLayout, eps); }
>                            ^
> make: *** [.build_release/src/caffe/layers/mkl_batch_norm_layer.o] Error 1
>

**Comment by sato-cloudian** [comment]
I forgot to mention, but am working on the latest.

> $ git show
> commit 5027e213952c1f4126127f5f8372700242fbe8ea
> Merge: 1801874 d3a83ee
> Author: emfomenk <evarist.m.fomenko@intel.com>
> Date:   Tue May 17 10:20:52 2016 +0200
> 
>     task-align-with-mkl2017-bu1: fixup: mkl2017: align with mkl2017 beta updat

**Comment by jreniecki** [comment]
Hello,
I'm sorry, some changes were pushed too early.  We'll fix it today.

**Comment by sato-cloudian** [comment]
I confirmed with the following build this was fixed.

> $ git show
> commit 31ad350536718ad8de30ae5f4a33bffc61dd8574
> Merge: fa1f3c7 589be3a
> Author: jreniecki <jacek.reniecki@intel.com>
> Date:   Wed May 18 14:50:53 2016 +0200
> 
>     task-align-with-mkl2017-bu1-fixup-fixup: Trigger new pre-review build :)
> 
>
